### ISSUE TITLE
Binpy shell fails to start

### ISSUE THREAD

**Issue by debugger22** [BinPy/BinPy#147]
I am not able to start binpy shell on linux. I am using the latest code of develop branch.
I checked it on two machines and both of them ended up with the same error

```
Traceback (most recent call last):
  File "/usr/local/bin/binpy", line 9, in <module>
    load_entry_point('BinPy==0.3', 'console_scripts', 'binpy')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2309, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2020, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'BinPy.Shell' from '/usr/local/lib/python2.7/dist-packages/BinPy-0.3-py2.7.egg/BinPy/Shell/__init__.pyc'> has no 'shellMain' attribute
```

**Comment by rajat974** [comment]
Fixed! See PR #137
