### ISSUE TITLE
Intermittent failure in counters

### ISSUE THREAD

**Issue by debugger22** [BinPy/BinPy#256]
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 532, in __bootstrap_inner
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 484, in run
  File "/home/travis/build/debugger22/BinPy/BinPy/connectors/linker.py", line 263, in connections_updater
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 150, in __exit__
  File "/opt/python/2.6.9/lib/python2.6/threading.py", line 137, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
..F...
======================================================================
FAIL: BinPy.tests.counters_tests.test_NBitDownCounter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/debugger22/BinPy/BinPy/tests/counters_tests.py", line 47, in test_NBitDownCounter
    0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1]
AssertionError
```

**Comment by ghost** [comment]
Even the IC 4017 ( Based on `DecadeCounter` ) Fails occasionally. And the tests ( for  IC 4017 and IC 4029 ) take a long time.

I'll better reimplement `counters.py`  using linker ?

**Comment by debugger22** [comment]
That seems more prominent. We can do that later. Leave it for me. :-)

**Comment by ghost** [comment]
Okay ! :)

**Comment by debugger22** [comment]
```
======================================================================
FAIL: BinPy.tests.test_analog_converters_buffers.test_A2D_AnalogBuffer_D2A
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/pypy-2.2.1/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/debugger22/BinPy/BinPy/tests/test_analog_converters_buffers.py", line 61, in test_A2D_AnalogBuffer_D2A
    as_list=False)
AssertionError
```
